server.port=8085
spring.application.name=user-management-system

# ==========================================
# Oracle XE Datasource Ayarları
# ==========================================
# Service Name XEPDB1 üzerinden Pluggable DB'ye bağlanıyoruz
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==========================================
# JPA / Hibernate & Oracle Dialect Ayarları
# ==========================================
# Geliştirme ortamında tabloları Entity modellerine göre otomatik senkronize et
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Konsolda çalıştırılan SQL ve DDL ifadelerini formatlı göster
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true