server.port=8085
spring.application.name=user-management-system

# ==========================================
# H2 Veritabanı & JPA / Hibernate Ayarları
# ==========================================
spring.datasource.url=jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Web Konsolu (http://localhost:8085/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate DDL Auto: Tabloları Entity modellerine göre otomatik oluşturur
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect