# Sunucu Port Yapılandırması (Varsayılan 8080 yerine kurumsal port)
server.port=8085

# Uygulama Meta Verileri
spring.application.name=user-management-system
application.version=1.0.0

# Log Formatı ve Seviyeleri
logging.level.com.thinx=DEBUG
logging.level.org.springframework.web=INFO